### ISSUE TITLE
Embycon error on startup

### ISSUE THREAD

**Issue by browned** [faush01/plugin.video.embycon#81]
Emby server 4.3.0.30
EmbyCon 1.9.53
Kodi 18.5/Titan MOD Skin.
Nvidia Shield TV

Log Error on startup.
2019-12-10 22:31:32.614 T:12257   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named PIL
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.embycon/service.py", line 26, in <module>
                                                from resources.lib.image_server import HttpImageServerThread
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.embycon/resources/lib/image_server.py", line 13, in <module>
                                                from PIL import ImageFilter, Image, ImageOps
                                            ImportError: No module named PIL
                                            -->End of Python script error report<--
2019-12-10 22:31:39.725 T:12207   ERROR: Misplaced +
2019-12-10 22:31:39.725 T:12207   ERROR: Error parsing boolean expression [string.contains(container.folderpath,plugin://plugin.program.ael) | string.contains(container.folderpath,plugin://plugin.program.advanced.launcher) | string.contains(container.folderpath,plugin://plugin.program.advanced.emulator.launcher)] +  + [skin.string(game.thumbshape.ps1,auto) | !skin.string(game.thumbshape.ps1)]
2019-12-10 22:31:39.725 T:12207   ERROR: Misplaced +
2019-12-10 22:31:39.725 T:12207   ERROR: Error parsing boolean expression [string.contains(container.folderpath,plugin://plugin.program.ael) | string.contains(container.folderpath,plugin://plugin.program.advanced.launcher) | string.contains(container.folderpath,plugin://plugin.program.advanced.emulator.launcher)] +  + skin.string(game.thumbshape.ps1)
2019-12-10 22:31:39.760 T:12207 WARNING: Trying to add unsupported control type 1

**Comment by browned** [comment]
EmbyCon loads ok by the looks of it, but nothing seems to play.

**Comment by killride** [comment]
Hi, Same issue to me since yesterday.

**Comment by faush01** [comment]
It looks like the PIL python module is not available on Nvidia Shield TV
Are you both using Nvidia Shield TV devices?

**Comment by killride** [comment]
Ni im using an mxq android 5 box tv. I have the same issue on few devices since yesterday. Did you put online a new version in the past 2 days?

**Comment by killride** [comment]
And I have an embycon error popping up on kodi

**Comment by JoshFink** [comment]
I'm having the same problem and YES, I am on an NVidia Shield.

**Comment by killride** [comment]
It appears only on the version 1.9.51 but with the stable 1.9.32

**Comment by JoshFink** [comment]
Stable 1.9.32 is working fine. Not sure what .51 fixed.

**Comment by browned** [comment]
Not sure what PIL is being used for in Embycon but some people are making references to using pygame instead of PIL for Android devices and apps.

**Comment by faush01** [comment]
Try that latest beta 1.9.54

This should stop the PIL load errors.

I have added some dynamic image creation for some of the lists in the addon menu, things like at A-Z and Pages listing now try to build dynamic images for the ListItems poster. I am suing PIL for this.

**Comment by browned** [comment]
Update is working with no errors. Thanks.

**Comment by faush01** [comment]
thanks for confirming, closing now
